name: Generate clients
on: push
jobs:
  generate-clients:
    runs-on: ubuntu-latest
    name: Example
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3
      uses: actions/setup-python@main
      with:
        python-version: 3.11

    - name: Install 
      run: >-
        python -m
        pip install .[doc]

    - name: Run server in background
      run: >-
        cd apps && uvicorn simple.main:app --proxy-headers --host 0.0.0.0 &
  
    - name: Generate OpenAPI document 
      run: curl localhost:8000/openapi.json > openapi.json

    - name: Cleanup old client
      run: rm -rf typescript-fetch-client/

    - name: Generate new client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: typescript-fetch

    - name: Commit new client
      run: |
        git config --global user.name 'xinetzone'
        git config --global user.email 'xinzone@outlook.com'
        git add typescript-fetch-client/
        git commit -am "Update typescript client"
        git push